server:
  port: 8080
  servlet:
    context-path: /GroceryShop

spring:
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=grocery_shop"
    username: sa
    password: 1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "ATDwgYF0Lqzb5jBEBUCSKmv48ovR3jlQdcM1yIMtoBE90VJqr9XzBuqQLASlWPV9"
